language: android

env:
  global:
    - ANDROID_TARGET=android-26
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-27
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

branches:
  only:
  - master

before_script:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v

script:
  - ./gradlew build jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)